name: 'proto api docs'
description: 'Generate Swagger API docs from protobuf files and push them to an S3 bucket'
branding:
  icon: 'edit-3'
  color: 'gray-dark'
inputs:
  GIT_TOKEN:
    description: 'Git token to use for cloning the repository containing the protobuf files'
    required: true
  PROTO_REPOSITORY:
    description: 'Protobuf files GitHub repository including the org name'
    required: true
  PROTO_BRANCH:
    description: 'Branch to clone'
    required: true
  MODULE_LIST_FILE_PATH:
    description: 'Path to file containing list of subdirectories of protos to clone'
    required: true
  AWS_S3_BUCKET:
    description: 'S3 bucket name'
    required: true
  AWS_REGION:
    description: 'AWS region'
    required: true
  DEST_DIR:
    description: 'Destination S3 directory'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key ID (required if using IAM user credentials)'
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key (required if using IAM user credentials)'
    required: false
  AWS_ROLE_ARN:
    description: 'AWS role ARN (required if using IAM role credentials)'
    required: false
  AWS_WEB_IDENTITY_TOKEN_FILE:
    description: 'AWS web identity token file path (required if using IAM role credentials)'
    required: false
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.GIT_TOKEN }}
    - ${{ inputs.PROTO_REPOSITORY }}
    - ${{ inputs.PROTO_BRANCH }}
    - ${{ inputs.MODULE_LIST_FILE_PATH }}
    - ${{ inputs.AWS_S3_BUCKET }}
    - ${{ inputs.AWS_REGION }}
    - ${{ inputs.DEST_DIR }}
    - ${{ inputs.AWS_ACCESS_KEY_ID }}
    - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - ${{ inputs.AWS_ROLE_ARN }}
    - ${{ inputs.AWS_WEB_IDENTITY_TOKEN_FILE }}
