name: 'proto api docs'
description: 'Generate swagger api docs from protobuf & push them to an S3 bucket'
branding:
  icon: 'edit-3'
  color: 'gray-dark'
inputs:
  GIT_TOKEN:
    description: 'Git token to use for cloning the repository containing the protobuf files'
    required: true
  PROTO_REPOSITORY:
    description: 'Protobuf files GitHub repository including the org name'
    required: true
  PROTO_BRANCH:
    description: 'Branch to clone'
    required: true
  MODULE_LIST_FILE_PATH:
    description: 'Path to file containing list of subdirectories of protos to clone'
    required: true
  AWS_S3_BUCKET:
    description: 'S3 bucket name'
    required: true
  AWS_ROLE_ARN:
    description: 'IAM role ARN to assume for S3 access'
    required: true
  AWS_ROLE_SESSION_NAME:
    description: 'Session name for the assumed role'
    required: false
    default: 's3-sync-session'
  AWS_REGION:
    description: 'AWS region'
    required: true
  DEST_DIR:
    description: 'Destination S3 directory'
    required: true
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
      - ${{ inputs.GIT_TOKEN }}
      - ${{ inputs.PROTO_REPOSITORY }}
      - ${{ inputs.PROTO_BRANCH }}
      - ${{ inputs.MODULE_LIST_FILE_PATH }}
      - ${{ inputs.AWS_S3_BUCKET }}
      - ${{ inputs.AWS_ROLE_ARN }}
      - ${{ inputs.AWS_ROLE_SESSION_NAME }}
      - ${{ inputs.AWS_REGION }}
      - ${{ inputs.DEST_DIR }}

