name: 'proto api docs'
description: 'Generate Swagger API docs from protobuf files and push them to an S3 bucket'
branding:
  icon: 'edit-3'
  color: 'gray-dark'
inputs:
  WORKFLOWGATEKEEPER_APP_ID:
    description: 'GitHub App ID for token generation'
    required: true
  WORKFLOWGATEKEEPER_PRIVATEKEY:
    description: 'GitHub App private key for token generation'
    required: true
  PROTO_REPOSITORY:
    description: 'Protobuf files GitHub repository including the org name'
    required: true
  PROTO_BRANCH:
    description: 'Branch to clone'
    required: true
  MODULE_LIST_FILE_PATH:
    description: 'Path to file containing list of subdirectories of protos to clone'
    required: true
  AWS_S3_BUCKET:
    description: 'S3 bucket name'
    required: true
  AWS_REGION:
    description: 'AWS region'
    required: true
  DEST_DIR:
    description: 'Destination S3 directory'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key ID (required if using IAM user credentials)'
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key (required if using IAM user credentials)'
    required: false
  AWS_ROLE_ARN:
    description: 'AWS role ARN (required if using IAM role credentials)'
    required: false
  AWS_WEB_IDENTITY_TOKEN_FILE:
    description: 'AWS web identity token file path (required if using IAM role credentials)'
    required: false
runs:
  using: "composite"
  steps:
    - uses: razorpay/create-github-app-token@latest
      name: Generate Github Token
      id: app-token
      with:
        app-id: ${{ inputs.WORKFLOWGATEKEEPER_APP_ID }}
        private-key: ${{ inputs.WORKFLOWGATEKEEPER_PRIVATEKEY }}
        repositories: "proto"
    
    - name: Run proto api docs generation
      uses: docker://./
      env:
        GIT_TOKEN: ${{ steps.app-token.outputs.token }}
        PROTO_REPOSITORY: ${{ inputs.PROTO_REPOSITORY }}
        PROTO_BRANCH: ${{ inputs.PROTO_BRANCH }}
        MODULE_LIST_FILE_PATH: ${{ inputs.MODULE_LIST_FILE_PATH }}
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
        DEST_DIR: ${{ inputs.DEST_DIR }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_ROLE_ARN: ${{ inputs.AWS_ROLE_ARN }}
        AWS_WEB_IDENTITY_TOKEN_FILE: ${{ inputs.AWS_WEB_IDENTITY_TOKEN_FILE }}
